# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'AHEPAHellas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AKSideMenu'

  target 'AHEPAHellasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AHEPAHellasUITests' do
    # Pods for testing
  end

end
